package com.marlo.achang.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/** This class was generated by the JAX-WS RI. JAX-WS RI 2.3.0.2 Generated source version: 2.2 */
@WebService(name = "SoapServer", targetNamespace = "http://achang.marlo.com/")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapServer {

  /**
   * @param arg0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(
      localName = "receive",
      targetNamespace = "http://achang.marlo.com/",
      className = "com.marlo.achang.wsimport.Receive")
  @ResponseWrapper(
      localName = "receiveResponse",
      targetNamespace = "http://achang.marlo.com/",
      className = "com.marlo.achang.wsimport.ReceiveResponse")
  @Action(
      input = "http://achang.marlo.com/SoapServer/receiveRequest",
      output = "http://achang.marlo.com/SoapServer/receiveResponse")
  public String receive(@WebParam(name = "arg0", targetNamespace = "") String arg0);
}
