image: maven:3.6.0-jdk-8-slim

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - .m2/repository/
    - customerorderms/target
    - productms/target
    - purchaseorderms/target
    - supplier-a/target
    - supplier-b/target
    - supplier-c/target

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean validate fmt:check sortpom:verify package
  artifacts:
    paths:
      - customerorderms/target
      - productms/target
      - purchaseorderms/target
      - supplier-a/target
      - supplier-b/target
      - supplier-c/target
  except:
    - tags

pages:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS jacoco:prepare-agent javadoc:javadoc site:site site:stage
    - mv target/staging public

  artifacts:
    paths:
    - customerorderms/target/*.jar
    - productms/target/*.jar
    - purchaseorderms/target/*.jar
    - supplier-a/target/*.jar
    - supplier-b/target/*.jar
    - supplier-c/target/*.jar
      - public
  only:
    - master
